# Generated by Django 4.1.7 on 2023-03-01 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='age',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='год')),
                ('description3', models.TextField(verbose_name='год')),
                ('url', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'год',
                'verbose_name_plural': 'года',
            },
        ),
        migrations.CreateModel(
            name='country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='страна')),
                ('description1', models.TextField(verbose_name='страна')),
                ('url', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'страна',
                'verbose_name_plural': 'страны',
            },
        ),
        migrations.CreateModel(
            name='denomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='номинал')),
                ('description2', models.TextField(verbose_name='номинал')),
                ('url', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'номинал',
                'verbose_name_plural': 'номиналы',
            },
        ),
        migrations.CreateModel(
            name='metal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='металл')),
                ('description4', models.TextField(verbose_name='металл')),
            ],
            options={
                'verbose_name': 'металл',
                'verbose_name_plural': 'металлы',
            },
        ),
        migrations.CreateModel(
            name='description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Монета')),
                ('img', models.ImageField(upload_to='ImgOsnova')),
                ('des', models.TextField(verbose_name='Описание')),
                ('url', models.SlugField(max_length=130, unique=True)),
                ('age', models.ManyToManyField(to='osnova.age', verbose_name='Год')),
                ('country', models.ManyToManyField(to='osnova.country', verbose_name='Страна')),
                ('denomination', models.ManyToManyField(to='osnova.denomination', verbose_name='Номинал')),
                ('metal', models.ManyToManyField(to='osnova.metal', verbose_name='Металл')),
            ],
            options={
                'verbose_name': 'описание',
                'verbose_name_plural': 'описание',
            },
        ),
    ]
